name: Dummy

on:
  workflow_dispatch:

jobs:
  build:
    name: Dev and Debug Workflows

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: git rev-parse HEAD
